lsb/views.py
from PIL import Image
from flask import Blueprint, request
from flask import render_template

from .bin_ascii import ascii_str_to_bin
from .forms import EncodeForm, DecodeForm

bp_lsb = Blueprint("lsb", __name__, url_prefix="/lsb")

STARTER: str = "#start#"
STARTER_LENGTH: int = len(STARTER)
BIN_STARTER: str = ascii_str_to_bin(STARTER)
BIN_STARTER_LENGTH: int = len(BIN_STARTER)
DELIMITER: str = "#end#"
DELIMITER_LENGTH: int = len(DELIMITER)
BIN_DELIMITER: str = ascii_str_to_bin(DELIMITER)
BIN_DELIMITER_LENGTH: int = len(BIN_DELIMITER)

# move this import down to avoid circular import
from .helpers import (
    verify_png,
    verify_ascii,
    verify_channel,
    check_if_msg_fit_in_img,
    encode,
    decode,
    verify_png_jpeg,
    buffer_and_convert_b64,
)


@bp_lsb.route("/")
def index():
    return render_template("lsb-index.html")


@bp_lsb.route("/encode/", methods=["GET", "POST"])
def encode_page():
    form = EncodeForm()
    if request.method != "POST" or not form.validate_on_submit():
        return render_template("lsb-encode.html", form=form)
    if not verify_ascii(form.message.data):
        return render_template(
            "lsb-encode.html", form=form, error="ASCII characters only."
        )
    if not verify_png_jpeg(form.image.data):
        return render_template("lsb-encode.html", form=form, error="PNG images only.")
    # Delimiter is used to signal the end of message
    msg_with_starter_and_delimiter: str = STARTER + form.message.data + DELIMITER
    bin_msg_with_starter_and_delimiter: str = ascii_str_to_bin(
        msg_with_starter_and_delimiter
    )
    consumed_bits: int = int(form.consumed_bits.data)
    image: Image = Image.open(form.image.data)
    channel: int = verify_channel(image)
    if not channel:
        return render_template(
            "lsb-encode.html", form=form, error="RGB or RGBA color channel only."
        )
    if not check_if_msg_fit_in_img(
        bin_msg_with_starter_and_delimiter, image, channel, consumed_bits
    ):
        return render_template(
            "lsb-encode.html", form=form, error="The message does not fit in the image."
        )
    result: Image = encode(bin_msg_with_starter_and_delimiter, image, consumed_bits)
    # Pillow Image objects can not be displayed in HTML, thus it is necessary to convert it to base64
    result_base64: str = buffer_and_convert_b64(result)
    return result_base64


@bp_lsb.route("/decode/", methods=["GET", "POST"])
def decode_page():
    form = DecodeForm()
    if request.method != "POST" or not form.validate_on_submit():
        return render_template("lsb-decode.html", form=form)
    if not verify_png(form.image.data):
        return render_template("lsb-decode.html", form=form, error="PNG images only.")
    consumed_bits: int = int(form.consumed_bits.data)
    image: Image = Image.open(form.image.data)
    channel: int = verify_channel(image)
    if not channel:
        return render_template(
            "lsb-decode.html", form=form, error="RGB or RGBA color channel only."
        )
    result: str = decode(image, consumed_bits)
    return result

prng/views.py
import json
import secrets

from PIL import Image
from flask import Blueprint, request
from flask import render_template

from lsb.bin_ascii import ascii_str_to_bin
from .forms import EncodeForm, DecodeForm

bp_prng = Blueprint("prng", __name__, url_prefix="/prng")

STARTER: str = "#start#"
STARTER_LENGTH: int = len(STARTER)
BIN_STARTER: str = ascii_str_to_bin(STARTER)
BIN_STARTER_LENGTH: int = len(BIN_STARTER)
DELIMITER: str = "#end#"
DELIMITER_LENGTH: int = len(DELIMITER)
BIN_DELIMITER: str = ascii_str_to_bin(DELIMITER)
BIN_DELIMITER_LENGTH: int = len(BIN_DELIMITER)

# move this import down to avoid circular import
from .helpers import (
    verify_png,
    verify_ascii,
    verify_channel,
    check_if_msg_fit_in_img,
    encode,
    decode,
    verify_png_jpeg,
    buffer_and_convert_b64,
)


@bp_prng.route("/")
def index():
    return render_template("prng-index.html")


@bp_prng.route("/encode/", methods=["GET", "POST"])
def encode_page():
    form = EncodeForm()
    if request.method != "POST" or not form.validate_on_submit():
        return render_template("prng-encode.html", form=form)
    if not verify_ascii(form.message.data):
        return render_template(
            "prng-encode.html", form=form, error="ASCII characters only."
        )
    if not verify_png_jpeg(form.image.data):
        return render_template("prng-encode.html", form=form, error="PNG images only.")
    # Delimiter is used to signal the end of message
    msg_with_starter_and_delimiter: str = STARTER + form.message.data + DELIMITER
    bin_msg_with_starter_and_delimiter: str = ascii_str_to_bin(
        msg_with_starter_and_delimiter
    )
    image: Image = Image.open(form.image.data)
    channel: int = verify_channel(image)
    if not channel:
        return render_template(
            "prng-encode.html", form=form, error="RGB or RGBA color channel only."
        )
    if not check_if_msg_fit_in_img(
        bin_msg_with_starter_and_delimiter, image, channel, 1
    ):
        return render_template(
            "prng-encode.html",
            form=form,
            error="The message does not fit in the image.",
        )
    if not form.seed.data:
        seed: str = secrets.token_hex(32)
    else:
        seed: str = form.seed.data
    result: Image = encode(bin_msg_with_starter_and_delimiter, image, channel, seed)
    # Pillow Image objects can not be displayed in HTML, thus it is necessary to convert it to base64
    result_base64: str = buffer_and_convert_b64(result)
    result_dict: dict = {"result-seed": seed, "result-img": result_base64}
    result_json = json.dumps(result_dict)
    return result_json


@bp_prng.route("/decode/", methods=["GET", "POST"])
def decode_page():
    form = DecodeForm()
    if request.method != "POST" or not form.validate_on_submit():
        return render_template("prng-decode.html", form=form)
    if not verify_png(form.image.data):
        return render_template("prng-decode.html", form=form, error="PNG images only.")
    seed: str = form.seed.data
    image: Image = Image.open(form.image.data)
    channel: int = verify_channel(image)
    if not channel:
        return render_template(
            "prng-decode.html", form=form, error="RGB or RGBA color channel only."
        )
    result: str = decode(image, seed)
    return result

templates/about.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='wall-of-text.css') }}">
{% endblock %}
{% block title %}<title>About</title>{% endblock %}
{% block main %}
    <main>
        <h2>About</h2>
        <div class="wall-of-text">
            <p>Copyright (c) 2023 Tran Hai Long.</p>
            <p>This website utilizes the following open source projects:</p>
            <ul>
                <li>
                    <a href="https://python-pillow.org/">Pillow</a> image processing
                    library
                </li>
                <li>
                    <a href="https://flask.palletsprojects.com/en/2.2.x/">Flask</a>
                    micro web framework
                </li>
                <li>
                    <a href="https://wtforms.readthedocs.io/en/3.0.x/">WTForms</a> and
                    <a href="https://flask-wtf.readthedocs.io/en/1.0.x/">Flask-WTF</a>
                    form processing plugins
                </li>
            </ul>
            <p>
                Source code for this website is available on <a
                    href="https://github.com/tran-hai-long/lsb_steganography">my Github</a>.
            </p>
        </div>
    </main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
    <script src="https://unpkg.com/htmx.org@1.9.2"
            integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
            crossorigin="anonymous"></script>
    {% block style %}{% endblock %}
    {% block title %}<title>Title</title>{% endblock %}
</head>
<body>
    {% block header %}
        <header>
            <a href="{{ url_for('index') }}" id="header-logo-link">
                <h1 id="header-logo">Image Steganography</h1>
            </a>
        </header>
    {% endblock %}
    {% block main %}
    {% endblock %}
    {% block footer %}
        <footer>
            <a href="https://github.com/tran-hai-long/lsb_steganography/wiki" class="footer-link">Wiki</a>
            <a href="{{ url_for('terms_of_use_page') }}" class="footer-link">Terms of
                Use</a>
            <a href="{{ url_for('privacy_policy_page') }}" class="footer-link">Privacy
                Policy</a>
            <a href="{{ url_for('about_page') }}" class="footer-link">About</a>
        </footer>
    {% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='index.css') }}">{% endblock %}
{% block title %}<title>Index</title>{% endblock %}
{% block main %}
    <main>
        <h2>Choose a steganography method</h2>
        <div class="button-div">
            <a href="{{ url_for('lsb.index') }}" class="outline-btn encode-decode-btn">
                LSB</a>
            <a href="{{ url_for('prng.index') }}" class="outline-btn encode-decode-btn">
                PRNG</a>
        </div>
    </main>
{% endblock %}

templates/lsb-decode.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='encode-decode.css') }}">
    <script src="/static/lsb-decode.js"></script>
{% endblock %}
{% block title %}<title>Decode</title>{% endblock %}
{% block main %}
    <main>
        {% if not result %}
            <p class="alert-box">Currently the site only supports ASCII messages and
                RGB/RGBA PNG images. Max image size 5MB.</p>
        {% endif %}
        <h2>Decode</h2>
        <form method="POST" enctype="multipart/form-data"
              action="{{ url_for('lsb.decode_page') }}">
            {{ form.csrf_token }}
            <div id="form-image">
                {{ form.image.label }}:<br>
                {{ form.image(accept="image/png") }}
                {% if form.image.errors %}
                    <ul>
                        {% for error in form.image.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            <br>
            <div id="form-consumed-bits">
                {{ form.consumed_bits.label }}<br>
                {% for choice in form.consumed_bits %}
                    <tr>
                        <td>{{ choice }}</td>
                        <td>{{ choice.label }}</td>
                    </tr>
                {% endfor %}
                {% if form.consumed_bits.errors %}
                    <ul>
                        {% for error in form.consumed_bits.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            {% if error %}<p class="text-error">{{ error }}</p>{% endif %}
        </form>
        <button id="submit-button">Submit</button>
        <p id="result-msg"></p>
    </main>
{% endblock %}

templates/lsb-encode-result-htmx.html
<img src="data:image/png;base64,{{ result | safe }}" alt="result image" id="result-img">

templates/lsb-encode.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='encode-decode.css') }}">
    <script src="/static/lsb-encode.js"></script>
{% endblock %}
{% block title %}<title>Encode</title>{% endblock %}
{% block main %}
    <main>
        {% if not result %}
            <p class="alert-box">Currently the site only supports ASCII messages and
                RGB/RGBA PNG/JPEG images. Max image size 5MB.</p>
        {% endif %}
        <h2>Encode</h2>
        <form method="POST" enctype="multipart/form-data"
              action="{{ url_for('lsb.encode_page') }}">
            {{ form.csrf_token }}
            <div id="form-message">
                {{ form.message.label }}:<br>
                {{ form.message(placeholder="Type here...") }}
                {% if form.message.errors %}
                    <ul>
                        {% for error in form.message.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            <br>
            <div id="form-image">
                {{ form.image.label }}:<br>
                {{ form.image(accept="image/png, image/jpeg") }}
                {% if form.image.errors %}
                    <ul>
                        {% for error in form.image.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            <br>
            <div id="form-consumed-bits">
                {{ form.consumed_bits.label }}<br>
                {% for choice in form.consumed_bits %}
                    <tr>
                        <td>{{ choice }}</td>
                        <td>{{ choice.label }}</td>
                    </tr>
                {% endfor %}
                {% if form.consumed_bits.errors %}
                    <ul>
                        {% for error in form.consumed_bits.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            {% if error %}<p class="text-error">{{ error }}</p>{% endif %}
        </form>
        <button id="submit-button">Submit</button>
        {#    Parse result image from base64 #}
        <br>
        <img src="data:image/png;base64,{{ result | safe }}" alt="result image" id="result-img">
    </main>
{% endblock %}

templates/lsb-index.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='index.css') }}">{% endblock %}
{% block title %}<title>LSB</title>{% endblock %}
{% block main %}
    <main>
        <h2>Do you want to encode or decode?</h2>
        <div class="button-div">
            <a href="{{ url_for('lsb.encode_page') }}"
               class="outline-btn encode-decode-btn">Encode</a>
            <a href="{{ url_for('lsb.decode_page') }}"
               class="outline-btn encode-decode-btn">Decode</a>
        </div>
    </main>
{% endblock %}

templates/privacy.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='wall-of-text.css') }}">
{% endblock %}
{% block title %}<title>Privacy Policy</title>{% endblock %}
{% block main %}
    <main>
        <h2>Privacy Policy</h2>
        <div class="wall-of-text">
            <p>I (the site owner) am not interested nor do I collect any of your data.
                Period.</p>
        </div>
    </main>
{% endblock %}

templates/prng-decode.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='encode-decode.css') }}">
    <script src="/static/prng-decode.js"></script>
{% endblock %}
{% block title %}<title>Decode</title>{% endblock %}
{% block main %}
    <main>
        {% if not result %}
            <p class="alert-box">Currently the site only supports ASCII messages and
                RGB/RGBA PNG images. Max image size 5MB.</p>
        {% endif %}
        <h2>Decode</h2>
        <form method="POST" enctype="multipart/form-data"
              action="{{ url_for('prng.decode_page') }}">
            {{ form.csrf_token }}
            <div id="form-image">
                {{ form.image.label }}:<br>
                {{ form.image(accept="image/png") }}
                {% if form.image.errors %}
                    <ul>
                        {% for error in form.image.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            <br>
            <div id="form-seed">
                {{ form.seed.label }}:<br>
                {{ form.seed(placeholder="Type here...") }}
                {% if form.seed.errors %}
                    <ul>
                        {% for error in form.seed.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            {% if error %}<p class="text-error">{{ error }}</p>{% endif %}
        </form>
        <button id="submit-button">Submit</button>
        <p id="result-msg"></p>
    </main>
{% endblock %}

templates/prng-encode-result-htmx.html
<div id="result">
    <div id="result-seed">
        <p>KEEP THIS SEED SAFE, YOU WILL NEED IT TO DECODE THE IMAGE:</p>
        <p>{{ seed }}</p>
    </div>
    <div>
        <img src="data:image/png;base64,{{ result | safe }}" alt="result image"
             id="result-img">
    </div>
</div>

templates/prng-encode.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='encode-decode.css') }}">
    <script src="/static/prng-encode.js"></script>
{% endblock %}
{% block title %}<title>Encode</title>{% endblock %}
{% block main %}
    <main>
        {% if not result %}
            <p class="alert-box">Currently the site only supports ASCII messages and
                RGB/RGBA PNG/JPEG images. Max image size 5MB.</p>
        {% endif %}
        <h2>Encode</h2>
        <form method="POST" enctype="multipart/form-data"
              action="{{ url_for('prng.encode_page') }}">
            {{ form.csrf_token }}
            <div id="form-message">
                {{ form.message.label }}:<br>
                {{ form.message(placeholder="Type here...") }}
                {% if form.message.errors %}
                    <ul>
                        {% for error in form.message.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            <br>
            <div id="form-image">
                {{ form.image.label }}:<br>
                {{ form.image(accept="image/png, image/jpeg") }}
                {% if form.image.errors %}
                    <ul>
                        {% for error in form.image.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            <br>
            <div id="form-seed">
                {{ form.seed.label }}:<br>
                {{ form.seed(placeholder="Type here...") }}
                {% if form.seed.errors %}
                    <ul>
                        {% for error in form.seed.errors %}
                            <li class="text-error">{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            {% if error %}<p class="text-error">{{ error }}</p>{% endif %}
        </form>
        <button id="submit-button">Submit</button>
        <br>
        {#    Parse result image from base64 #}
        <p id="result-seed">{{ seed }}</p>
        <img src="data:image/png;base64,{{ result | safe }}" alt="result image" id="result-img">
    </main>
{% endblock %}

templates/prng-index.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='index.css') }}">{% endblock %}
{% block title %}<title>PRNG</title>{% endblock %}
{% block main %}
    <main>
        <h2>Do you want to encode or decode?</h2>
        <div class="button-div">
            <a href="{{ url_for('prng.encode_page') }}"
               class="outline-btn encode-decode-btn">Encode</a>
            <a href="{{ url_for('prng.decode_page') }}"
               class="outline-btn encode-decode-btn">Decode</a>
        </div>
    </main>
{% endblock %}

templates/tou.html
{% extends "base.html" %}
{% block  style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='wall-of-text.css') }}">
{% endblock %}
{% block title %}<title>Terms of Use</title>{% endblock %}
{% block main %}
    <main>
        <h2>Terms of Use</h2>
        <div class="wall-of-text">
            <p>By using this website's service you agree that I (the site owner) am not
                responsible for anything you upload here.</p>
            <p>This website is for demonstration purpose and should not be used for
                encoding confidental documents.</p>
        </div>
    </main>
{% endblock %}